---
app: release-flask-postgres-count
auto_deploy: true
context: release-iewk7f
domain: docs.hubofhubs.com
repo_name: sixhobbits/release-flask-postgres-count
hostnames:
- count: count-release-flask-postgres-count-${env_id}.${domain}
environment_templates:
- name: ephemeral
- name: permanent
resources:
  cpu:
    limits: 1000m
    requests: 100m
  memory:
    limits: 1Gi
    requests: 100Mi
  replicas: 1
services:
- name: count 
  image: sixhobbits/release-flask-postgres-count/count
  build:
    context: "./count"
  has_repo: true
  static: false
  args:
  - python
  - app.py
  ports:
  - type: node_port
    target_port: '80'
    port: '5000'
- name: db
  image: postgres:14
  volumes:
  - type: persistent
    name: postgres-data
    mount_path: "/tmp/data"
  ports:
  - type: container_port
    port: '5432'
  storage:
    size: 10Gi
    type: aws-efs
workflows:
- name: setup
  order_from:
  - services.all
- name: teardown
  parallelize:
  - step: remove_environment
    tasks:
    - release.remove_environment
- name: patch
  order_from:
  - services.count

